#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class SpotifyIPCCredential:
  """
  Attributes:
   - _username
   - _passwd
   - _uuid
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, '_username', None, None, ), # 1
    (2, TType.STRING, '_passwd', None, None, ), # 2
    (3, TType.STRING, '_uuid', None, None, ), # 3
  )

  def __init__(self, _username=None, _passwd=None, _uuid=None,):
    self._username = _username
    self._passwd = _passwd
    self._uuid = _uuid

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self._username = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self._passwd = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self._uuid = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('SpotifyIPCCredential')
    if self._username is not None:
      oprot.writeFieldBegin('_username', TType.STRING, 1)
      oprot.writeString(self._username)
      oprot.writeFieldEnd()
    if self._passwd is not None:
      oprot.writeFieldBegin('_passwd', TType.STRING, 2)
      oprot.writeString(self._passwd)
      oprot.writeFieldEnd()
    if self._uuid is not None:
      oprot.writeFieldBegin('_uuid', TType.STRING, 3)
      oprot.writeString(self._uuid)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self._username is None:
      raise TProtocol.TProtocolException(message='Required field _username is unset!')
    if self._passwd is None:
      raise TProtocol.TProtocolException(message='Required field _passwd is unset!')
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
