/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef spotify_ipc_CONSTANTS_H
#define spotify_ipc_CONSTANTS_H

#include "spotify_ipc_types.h"



class spotify_ipcConstants {
 public:
  spotify_ipcConstants();

};

extern const spotify_ipcConstants g_spotify_ipc_constants;



#endif
