/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef spotify_types_CONSTANTS_H
#define spotify_types_CONSTANTS_H

#include "spotify_types_types.h"



class spotify_typesConstants {
 public:
  spotify_typesConstants();

};

extern const spotify_typesConstants g_spotify_types_constants;



#endif
