/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef spotify_CONSTANTS_H
#define spotify_CONSTANTS_H

#include "spotify_types.h"



class spotifyConstants {
 public:
  spotifyConstants();

};

extern const spotifyConstants g_spotify_constants;



#endif
