// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

//Boost.
#include <boost/algorithm/string.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/filesystem.hpp>
#include <boost/program_options.hpp>

#include <iostream>
#include <cstring>
#include <cerrno>
#include <string>

#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#include "Spotify.h"

#include "xplodify_sess.h"
#include "xplodify_plc.h"
#include "xplodify_pl.h"
#include "spotify_cust.h"


using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

//define the operators
//these must be moved to their own file with other possible
//definitions for thrift generated code.
bool SpotifyTrack::operator < (const SpotifyTrack & other) const 
{
    return (this->_id - other._id) < 0;
}

bool SpotifyCredential::operator < (const SpotifyCredential & other) const 
{
    return this->_username.compare(other._username) < 0;
}


XplodifyServer::XplodifyServer(bool multisession)
    : Runnable()
    , Lockable()
    , SpotifyHandler()
    , m_sess_it(m_session_cache.get<0>().begin())
    , m_active_session()
    , m_multi(multisession)
{

}


void XplodifyServer::run() 
{
    //process timer events?
#if 0
        m_io.poll();
        m_io.reset();
#endif
}

void XplodifyServer::remove_from_cache(const std::string& uuid) {
    bool move_on = false;
    sess_map_entry aux_entry(*m_sess_it);
    sess_map_sequenced::iterator sess_it = m_sess_it;
    if(++sess_it == m_session_cache.get<0>().end()) {
        sess_it = m_session_cache.get<0>().begin();
    }
    if(aux_entry._uuid == uuid) {
        move_on = true;
    }
    sess_map_by_uuid& sess_by_uuid = m_session_cache.get<1>();
    size_t n = sess_by_uuid.erase(uuid);

    //fix the potentially invalidated iterator.
    if(n) {
        if(move_on) {
            m_sess_it = sess_it;
        } else {
            m_sess_it = m_session_cache.get<0>().iterator_to(aux_entry);
        }
    }
}

void XplodifyServer::check_in(SpotifyCredential& _return, const SpotifyCredential& cred) {
    std::string uuid_str = sh.check_in();
    _return = cred;
    _return.__set__uuid(uuid_str); //Empty string is a failure to check in.
}

bool XplodifyServer::check_out(const SpotifyCredential& cred) {
    //TODO
    return true;
}

bool XplodifyServer::loginSession(const SpotifyCredential& cred) {

    bool logging_in = sh.login(cred._uuid, cred._username, cred._password);

    if(logging_in) {
#ifdef _DEBUG
        std::cout << "starting timer for session: "<< uuid_str <<"\n";
#endif
        //no transfer of ownership, we're good with raw pointers.
        boost::asio::deadline_timer * t = new boost::asio::deadline_timer(m_io);
        t->expires_from_now(boost::posix_time::seconds(LOGIN_TO));
        t->async_wait(boost::bind(&XplodifyServer::login_timeout,
                    this, boost::asio::placeholders::error, cred._uuid));

        m_timers.insert(std::pair< std::string, boost::asio::deadline_timer *>(uuid_str, t));

    }
    return logging_in;
}
void XplodifyServer::login_timeout(const boost::system::error_code&,
        std::string uuid) {
#ifdef _DEBUG
    std::cout << "Event timeout for login: " << uuid << " Checking status...\n";
#endif
    timer_map::iterator it = m_timers.find(uuid);

    //Free up resources, cleanup.
    if(it != m_timers.end()) {
        lock();
        delete it->second;
        m_timers.erase(it);
        unlock();
    } else {
        return;
    }

    //check session status...
    bool logged = sh.login_status(uuid);

    if(logged) {
#ifdef _DEBUG
        std::cout << "Session: " << uuid << " Succesfully logged in ...\n";
#endif
        return;
    }

#if 0
    //not logged in, cleanup.
    lock();

    sh.check_out(uuid);
    remove_from_cache(uuid);

    sess->flush();
    sess.reset();
    unlock();
#endif

    update_timestamp();
}

bool XplodifyServer::isLoggedIn(const SpotifyCredential& cred) {

    return sh.login_status(cred._uuid);
}

int64_t XplodifyServer::getStateTS(const SpotifyCredential& cred) {
    int64_t ts;
    boost::shared_ptr< XplodifySession > 
        sess = get_session(cred._uuid);

    if(!sess)
        return false;

    lock();
    ts = m_ts;
    unlock();

    return ts;
}

int64_t XplodifyServer::getSessionStateTS(const SpotifyCredential& cred) {

    boost::shared_ptr< XplodifySession > 
        sess = get_session(cred._uuid);

    if(!sess)
        return false;

    return sess->get_state_ts();
}

void XplodifyServer::logoutSession(const SpotifyCredential& cred) {


    update_timestamp();
    return;
}

void XplodifyServer::sendCommand(const SpotifyCredential& cred, const SpotifyCmd::type cmd) {
    std::cout << "sendCommand" << std::endl;

    boost::shared_ptr<XplodifySession> sess = get_session(cred._uuid);
    if(!sess) {
        return;
    }

    switch(cmd){
        case SpotifyCmd::PLAY:
            sess->start_playback();
            break;
        case SpotifyCmd::PAUSE:
            sess->stop_playback();
#if 0
            audio_fifo_flush_now();
            audio_fifo_set_reset(audio_fifo(), 1);
#endif
            break;
        case SpotifyCmd::NEXT:
        case SpotifyCmd::PREV:
            sess->end_of_track();
            break;
        case SpotifyCmd::RAND:
        case SpotifyCmd::LINEAR:
        case SpotifyCmd::REPEAT_ONE:
        case SpotifyCmd::REPEAT:
            sess->set_mode(cmd);
            break;
        default:
            break;
    }

    update_timestamp();
    return;
}


void XplodifyServer::search(SpotifyPlaylist& _return, const SpotifyCredential& cred,
		const SpotifySearch& criteria) {
    // Your implementation goes here
    printf("search\n");
    boost::shared_ptr<XplodifySession> sess = get_session(cred._uuid);
    if(!sess) {
        return;
    }
}

void XplodifyServer::getPlaylists(SpotifyPlaylistList& _return, const SpotifyCredential& cred) 
{
    boost::shared_ptr<XplodifySession> sess = get_session(cred._uuid);
    if(!sess) {
        return;
    }
    boost::shared_ptr<XplodifyPlaylistContainer> pc = sess->get_pl_container();
    if(!pc) {
        return;
    }

    int n =  pc->get_num_playlists();
#ifdef _DEBUG
    std::cout << "About to retrieve " << n << "playlists.";
#endif
    for (int i = 0; i<n; ++i)
    {
        boost::shared_ptr<XplodifyPlaylist> pl = pc->get_playlist(i);
        std::string plstr(pl->get_name());
        _return.insert(plstr);
    }

    return;

}

void XplodifyServer::getPlaylist(SpotifyPlaylist& _return, const SpotifyCredential& cred,
        const int32_t plist_id) {
    // Your implementation goes here
    boost::shared_ptr<XplodifySession> sess = get_session(cred._uuid);
    if(!sess) {
        return;
    }

    boost::shared_ptr<XplodifyPlaylistContainer> pc = sess->get_pl_container();
    if(!pc) {
        return;
    }

    boost::shared_ptr<XplodifyPlaylist> pl = pc->get_playlist(plist_id);

    if(!pl) {
        return;
    }

    for(unsigned int j = 0 ; j < pl->get_num_tracks() ; j++ ) {
        boost::shared_ptr<XplodifyTrack> tr = pl->get_track_at(j);
#ifdef _DEBUG
        if(!tr->is_loaded()) {
            std::cout << "Track at index: "<<  j << " is loading" << std::endl;
        }
#endif
        int duration = tr->get_duration(); //millisecs?
        SpotifyTrack spt;

        spt.__set__id( tr->get_index() );
        spt.__set__name( tr->get_name() );
        spt.__set__artist( tr->get_artist(0) ); //first artist (this sucks).
        spt.__set__minutes( duration / 60000 );
        spt.__set__seconds( (duration / 1000) % 60 );
        spt.__set__popularity( tr->get_popularity() );
        spt.__set__starred( tr->is_starred() );
        spt.__set__genre( "unknown" );
        _return.push_back(spt);
    }

    return;
}

void XplodifyServer::getPlaylistByName(
        SpotifyPlaylist& _return, const SpotifyCredential& cred,
        const std::string& name) {

#ifdef _DEBUG
    std::cout << "getPlaylistByName: " << name << "\n";
#endif

    boost::shared_ptr<XplodifySession> sess = get_session(cred._uuid);
    if(!sess) {
        return;
    }


    boost::shared_ptr<XplodifyPlaylistContainer> pc = sess->get_pl_container();
    if(!pc) {
        return;
    }

    boost::shared_ptr<XplodifyPlaylist> pl = pc->get_playlist(name);
    if(!pl) {
        return;
    }

    for(unsigned int j = 0 ; j < pl->get_num_tracks() ; j++ ) {
        boost::shared_ptr<XplodifyTrack> tr = pl->get_track_at(j);
        if(tr->is_loaded()) {
            int duration = tr->get_duration(); //millisecs?
            //boost::shared_ptr<SpotifyTrack> spt(new SpotifyTrack());
            SpotifyTrack spt;

            spt.__set__id( tr->get_index() );
            spt.__set__name( tr->get_name() );
            spt.__set__artist( tr->get_artist(0) ); //first artist (this sucks).
            spt.__set__minutes( duration / 60000 );
            spt.__set__seconds( (duration / 1000) % 60 );
            spt.__set__popularity( tr->get_popularity() );
            spt.__set__starred( tr->is_starred() );
            spt.__set__genre( "unknown" );
            _return.push_back(spt);
        }
#ifdef _DEBUG
        else {
            std::cout << "Track at index:  "<<  j << " is loading" << std::endl;
        }
#endif
    }
#ifdef _DEBUG
    SpotifyPlaylist::const_iterator it;
    for(it = _return.begin() ; it != _return.end() ; it++) {
        std::cout << (*it)._name << "\n";
    }
#endif

    return;
}

void XplodifyServer::selectPlaylist(const SpotifyCredential& cred, const std::string& playlist) {

    boost::shared_ptr<XplodifySession> sess = get_session(cred._uuid);
    if(!sess) {
        return;
    }

    sess->set_active_playlist(playlist);

}
void XplodifyServer::selectPlaylistById(const SpotifyCredential& cred, const int32_t plist_id) {
    // Your implementation goes here
    printf("selectPlaylist\n");
    boost::shared_ptr< XplodifySession > sess = get_session(cred._uuid);
    if(!sess) {
	return;
    }

    sess->set_active_playlist(plist_id);
}

void XplodifyServer::selectTrack(const SpotifyCredential& cred, const std::string& track) {

    //TODO
    boost::shared_ptr< XplodifySession > sess = get_session(cred._uuid);
    if(!sess) {
        return;
    }

#ifdef _DEBUG
    std::cout << "Selecting track " << track << " for session with uuid: " 
        << sess->m_uuid << std::endl;
#endif
    sess->set_track(track);
    return;

}
void XplodifyServer::selectTrackById(const SpotifyCredential& cred, const int32_t track_id) {

    //TODO
    boost::shared_ptr< XplodifySession > sess = get_session(cred._uuid);
    if(!sess) {
        return;
    }

    sess->set_track(track_id);
    return;
}

bool XplodifyServer::merge2playlist(const SpotifyCredential& cred, const std::string& pl,
		const SpotifyPlaylist& tracks) {
    boost::shared_ptr< XplodifySession > sess = get_session(cred._uuid);
    if(!sess) {
        return false;
    }
    // Your implementation goes here
    printf("merge2playlist\n");
    return true;
}

bool XplodifyServer::add2playlist(const SpotifyCredential& cred, const std::string& pl,
		const SpotifyTrack& track) {
    boost::shared_ptr< XplodifySession > sess = get_session(cred._uuid);
    if(!sess) {
        return false;
    }
    // Your implementation goes here
    printf("add2playlist\n");
    return true;
}

void XplodifyServer::whats_playing(SpotifyTrack& _return) {

    if(!m_active_session) {
        return;
    }
    boost::shared_ptr<XplodifyTrack> tr( m_active_session->get_track());
    if(!tr) {
        return;
    }

    int duration = tr->get_duration(); 

    _return.__set__id( tr->get_index() );
    _return.__set__name( tr->get_name() );
    _return.__set__artist( tr->get_artist(0) ); //first artist (this sucks).
    _return.__set__minutes( duration / 60000 );
    _return.__set__seconds( (duration / 1000) % 60 );
    _return.__set__popularity( tr->get_popularity() );
    _return.__set__starred( tr->is_starred() );
    _return.__set__genre( "unknown" );

    return;
}

int XplodifyServer::music_playback(const sp_audioformat * format, 
        const void * frames, int num_frames) {
    //EMPTY FOR NOW: complying with interface
    return 0;
}
void XplodifyServer::audio_fifo_stats(sp_audio_buffer_stats *stats) {
    //EMPTY FOR NOW: complying with interface
    return;
}
void XplodifyServer::audio_fifo_flush_now(void) {
    //EMPTY FOR NOW: complying with interface
    return;
}

boost::shared_ptr<XplodifySession> XplodifyServer::get_session(const std::string& uuid) {

    sess_map_by_uuid& sess_by_uuid = m_session_cache.get<1>();

    sess_map_by_uuid::iterator sit = sess_by_uuid.find(uuid);
    if( sit == m_session_cache.get<1>().end() ) {
        return boost::shared_ptr<XplodifySession>();
    }

    return sit->session;
}

boost::shared_ptr<XplodifySession> XplodifyServer::get_session(const sp_session * sps) {

    sess_map_by_sessptr& sessByPtr = m_session_cache.get<2>();

    sess_map_by_sessptr::iterator sit = sessByPtr.find(reinterpret_cast<uintptr_t>(sps));
    if( sit == m_session_cache.get<2>().end() ) {
        return boost::shared_ptr<XplodifySession>();
    }

    return sit->session;
}

boost::shared_ptr<XplodifySession> XplodifyServer::getActiveSession(void) {
    return m_active_session;
}
void XplodifyServer::setActiveSession(boost::shared_ptr<XplodifySession> session) {
    m_active_session = session;
}

//we also need to be able to search by sp_session, that's quite important; callbacks rely very heavily
//on it.
sp_playlistcontainer * XplodifyServer::getPlaylistContainer(SpotifyCredential& cred) {
    boost::shared_ptr<XplodifySession> sess = get_session(cred._uuid);
    if(!sess) {
	return NULL;
    }

    return sp_session_playlistcontainer(sess->get_session());
}


void XplodifyServer::set_playback_done(bool done)
{
    lock();
    m_playback_done = done;
    unlock();
}

void XplodifyServer::notify_main_thread(void)
{
    lock();
    m_notify_events = 1;
    cond_signal();
    unlock();
}


void XplodifyServer::update_timestamp(void) {
    lock();
    m_ts = std::time(NULL);
    unlock();
}

std::string XplodifyServer::get_cachedir() {
    return m_sp_cachedir;
}

namespace {
    const uint32_t SRV_BASE_PORT=9090;
}

int main(int argc, char **argv) {
    uint32_t port, child_port;
    bool multi = true;

    pid_t master_pid, slave_pid;

    namespace po = boost::program_options; 
    po::options_description desc("Options"); 
    desc.add_options() 
        ("help", "Print help messages") 
        ("port", po::value<uint32_t>(&port)->default_value(SRV_BASE_PORT),"base port for server") 
        ("mono", "server mode: mono session enabled."); 

    po::variables_map vm;
    po::store(po::parse_command_line(argc, argv, desc), vm);
    po::notify(vm);

    if(vm.count("help")) {
        std::cout << desc << std::endl;
        return 1;
    }

    if(vm.count("mono")) {
        multi = false;
        child_port = port + 1;
    }

    if(multi) {
        master_pid = fork();
        if(!master_pid) { //MASTER CHILD process
            //TODO Boost service.
            exit(0);
        }

        slave_pid = fork();
        if(!slave_pid) { //SLAVE CHILD process
            //TODO> Boost service.
            exit(0);
        }
    }

    //XplodifyServer
    boost::shared_ptr<XplodifyServer> sHandler(new XplodifyServer(multi));

    //THRIFT Server
    boost::shared_ptr<TProcessor> processor(new SpotifyProcessor(sHandler));
    boost::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    boost::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    boost::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);

    //make tmp dir
    boost::filesystem::path dir(sHandler->get_cachedir());
    if(!boost::filesystem::create_directory(dir)) {
        //TODO: proper cleanup
        exit(1);
    }

    sHandler->start();
    server.serve();

    //TODO: proper cleanup
    int status;
    pid_t done;

    if(!(done = waitpid(master_pid, &status, 0))) {
        std::cerr << strerror(errno) << std::endl;
        return -1;
    }
    if(!(done = waitpid(slave_pid, &status, 0))) {
        std::cerr << strerror(errno) << std::endl;
        return -1;
    }

    return 0;
}

