/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Spotify_H
#define Spotify_H

#include <TProcessor.h>
#include "spotify_types.h"



class SpotifyIf {
 public:
  virtual ~SpotifyIf() {}
  virtual void initiateSession(SpotifyCredential& _return, const SpotifyCredential& cred) = 0;
  virtual void logoutSession(const SpotifyCredential& cred) = 0;
  virtual void sendCommand(const SpotifyCredential& cred, const SpotifyCmd::type cmd) = 0;
  virtual void search(SpotifyPlaylist& _return, const SpotifyCredential& cred, const SpotifySearch& criteria) = 0;
  virtual void getPlaylists(SpotifyPlaylistList& _return, const SpotifyCredential& cred) = 0;
  virtual void getPlaylist(SpotifyPlaylist& _return, const SpotifyCredential& cred, const int32_t plist_id) = 0;
  virtual void getPlaylistByName(SpotifyPlaylist& _return, const SpotifyCredential& cred, const std::string& name) = 0;
  virtual void selectPlaylist(const SpotifyCredential& cred, const std::string& playlist) = 0;
  virtual bool merge2playlist(const SpotifyCredential& cred, const std::string& pl, const SpotifyPlaylist& tracks) = 0;
  virtual bool add2playlist(const SpotifyCredential& cred, const std::string& pl, const SpotifyTrack& track) = 0;
  virtual void whats_playing(SpotifyTrack& _return) = 0;
};

class SpotifyNull : virtual public SpotifyIf {
 public:
  virtual ~SpotifyNull() {}
  void initiateSession(SpotifyCredential& /* _return */, const SpotifyCredential& /* cred */) {
    return;
  }
  void logoutSession(const SpotifyCredential& /* cred */) {
    return;
  }
  void sendCommand(const SpotifyCredential& /* cred */, const SpotifyCmd::type /* cmd */) {
    return;
  }
  void search(SpotifyPlaylist& /* _return */, const SpotifyCredential& /* cred */, const SpotifySearch& /* criteria */) {
    return;
  }
  void getPlaylists(SpotifyPlaylistList& /* _return */, const SpotifyCredential& /* cred */) {
    return;
  }
  void getPlaylist(SpotifyPlaylist& /* _return */, const SpotifyCredential& /* cred */, const int32_t /* plist_id */) {
    return;
  }
  void getPlaylistByName(SpotifyPlaylist& /* _return */, const SpotifyCredential& /* cred */, const std::string& /* name */) {
    return;
  }
  void selectPlaylist(const SpotifyCredential& /* cred */, const std::string& /* playlist */) {
    return;
  }
  bool merge2playlist(const SpotifyCredential& /* cred */, const std::string& /* pl */, const SpotifyPlaylist& /* tracks */) {
    bool _return = false;
    return _return;
  }
  bool add2playlist(const SpotifyCredential& /* cred */, const std::string& /* pl */, const SpotifyTrack& /* track */) {
    bool _return = false;
    return _return;
  }
  void whats_playing(SpotifyTrack& /* _return */) {
    return;
  }
};

typedef struct _Spotify_initiateSession_args__isset {
  _Spotify_initiateSession_args__isset() : cred(false) {}
  bool cred;
} _Spotify_initiateSession_args__isset;

class Spotify_initiateSession_args {
 public:

  Spotify_initiateSession_args() {
  }

  virtual ~Spotify_initiateSession_args() throw() {}

  SpotifyCredential cred;

  _Spotify_initiateSession_args__isset __isset;

  bool operator == (const Spotify_initiateSession_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    return true;
  }
  bool operator != (const Spotify_initiateSession_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_initiateSession_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_initiateSession_pargs {
 public:


  virtual ~Spotify_initiateSession_pargs() throw() {}

  const SpotifyCredential* cred;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_initiateSession_result__isset {
  _Spotify_initiateSession_result__isset() : success(false) {}
  bool success;
} _Spotify_initiateSession_result__isset;

class Spotify_initiateSession_result {
 public:

  Spotify_initiateSession_result() {
  }

  virtual ~Spotify_initiateSession_result() throw() {}

  SpotifyCredential success;

  _Spotify_initiateSession_result__isset __isset;

  bool operator == (const Spotify_initiateSession_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Spotify_initiateSession_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_initiateSession_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_initiateSession_presult__isset {
  _Spotify_initiateSession_presult__isset() : success(false) {}
  bool success;
} _Spotify_initiateSession_presult__isset;

class Spotify_initiateSession_presult {
 public:


  virtual ~Spotify_initiateSession_presult() throw() {}

  SpotifyCredential* success;

  _Spotify_initiateSession_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Spotify_logoutSession_args__isset {
  _Spotify_logoutSession_args__isset() : cred(false) {}
  bool cred;
} _Spotify_logoutSession_args__isset;

class Spotify_logoutSession_args {
 public:

  Spotify_logoutSession_args() {
  }

  virtual ~Spotify_logoutSession_args() throw() {}

  SpotifyCredential cred;

  _Spotify_logoutSession_args__isset __isset;

  bool operator == (const Spotify_logoutSession_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    return true;
  }
  bool operator != (const Spotify_logoutSession_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_logoutSession_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_logoutSession_pargs {
 public:


  virtual ~Spotify_logoutSession_pargs() throw() {}

  const SpotifyCredential* cred;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_sendCommand_args__isset {
  _Spotify_sendCommand_args__isset() : cred(false), cmd(false) {}
  bool cred;
  bool cmd;
} _Spotify_sendCommand_args__isset;

class Spotify_sendCommand_args {
 public:

  Spotify_sendCommand_args() {
  }

  virtual ~Spotify_sendCommand_args() throw() {}

  SpotifyCredential cred;
  SpotifyCmd::type cmd;

  _Spotify_sendCommand_args__isset __isset;

  bool operator == (const Spotify_sendCommand_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    if (!(cmd == rhs.cmd))
      return false;
    return true;
  }
  bool operator != (const Spotify_sendCommand_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_sendCommand_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_sendCommand_pargs {
 public:


  virtual ~Spotify_sendCommand_pargs() throw() {}

  const SpotifyCredential* cred;
  const SpotifyCmd::type* cmd;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_search_args__isset {
  _Spotify_search_args__isset() : cred(false), criteria(false) {}
  bool cred;
  bool criteria;
} _Spotify_search_args__isset;

class Spotify_search_args {
 public:

  Spotify_search_args() {
  }

  virtual ~Spotify_search_args() throw() {}

  SpotifyCredential cred;
  SpotifySearch criteria;

  _Spotify_search_args__isset __isset;

  bool operator == (const Spotify_search_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    if (!(criteria == rhs.criteria))
      return false;
    return true;
  }
  bool operator != (const Spotify_search_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_search_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_search_pargs {
 public:


  virtual ~Spotify_search_pargs() throw() {}

  const SpotifyCredential* cred;
  const SpotifySearch* criteria;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_search_result__isset {
  _Spotify_search_result__isset() : success(false) {}
  bool success;
} _Spotify_search_result__isset;

class Spotify_search_result {
 public:

  Spotify_search_result() {
  }

  virtual ~Spotify_search_result() throw() {}

  SpotifyPlaylist success;

  _Spotify_search_result__isset __isset;

  bool operator == (const Spotify_search_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Spotify_search_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_search_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_search_presult__isset {
  _Spotify_search_presult__isset() : success(false) {}
  bool success;
} _Spotify_search_presult__isset;

class Spotify_search_presult {
 public:


  virtual ~Spotify_search_presult() throw() {}

  SpotifyPlaylist* success;

  _Spotify_search_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Spotify_getPlaylists_args__isset {
  _Spotify_getPlaylists_args__isset() : cred(false) {}
  bool cred;
} _Spotify_getPlaylists_args__isset;

class Spotify_getPlaylists_args {
 public:

  Spotify_getPlaylists_args() {
  }

  virtual ~Spotify_getPlaylists_args() throw() {}

  SpotifyCredential cred;

  _Spotify_getPlaylists_args__isset __isset;

  bool operator == (const Spotify_getPlaylists_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    return true;
  }
  bool operator != (const Spotify_getPlaylists_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_getPlaylists_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_getPlaylists_pargs {
 public:


  virtual ~Spotify_getPlaylists_pargs() throw() {}

  const SpotifyCredential* cred;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_getPlaylists_result__isset {
  _Spotify_getPlaylists_result__isset() : success(false) {}
  bool success;
} _Spotify_getPlaylists_result__isset;

class Spotify_getPlaylists_result {
 public:

  Spotify_getPlaylists_result() {
  }

  virtual ~Spotify_getPlaylists_result() throw() {}

  SpotifyPlaylistList success;

  _Spotify_getPlaylists_result__isset __isset;

  bool operator == (const Spotify_getPlaylists_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Spotify_getPlaylists_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_getPlaylists_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_getPlaylists_presult__isset {
  _Spotify_getPlaylists_presult__isset() : success(false) {}
  bool success;
} _Spotify_getPlaylists_presult__isset;

class Spotify_getPlaylists_presult {
 public:


  virtual ~Spotify_getPlaylists_presult() throw() {}

  SpotifyPlaylistList* success;

  _Spotify_getPlaylists_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Spotify_getPlaylist_args__isset {
  _Spotify_getPlaylist_args__isset() : cred(false), plist_id(false) {}
  bool cred;
  bool plist_id;
} _Spotify_getPlaylist_args__isset;

class Spotify_getPlaylist_args {
 public:

  Spotify_getPlaylist_args() : plist_id(0) {
  }

  virtual ~Spotify_getPlaylist_args() throw() {}

  SpotifyCredential cred;
  int32_t plist_id;

  _Spotify_getPlaylist_args__isset __isset;

  bool operator == (const Spotify_getPlaylist_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    if (!(plist_id == rhs.plist_id))
      return false;
    return true;
  }
  bool operator != (const Spotify_getPlaylist_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_getPlaylist_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_getPlaylist_pargs {
 public:


  virtual ~Spotify_getPlaylist_pargs() throw() {}

  const SpotifyCredential* cred;
  const int32_t* plist_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_getPlaylist_result__isset {
  _Spotify_getPlaylist_result__isset() : success(false) {}
  bool success;
} _Spotify_getPlaylist_result__isset;

class Spotify_getPlaylist_result {
 public:

  Spotify_getPlaylist_result() {
  }

  virtual ~Spotify_getPlaylist_result() throw() {}

  SpotifyPlaylist success;

  _Spotify_getPlaylist_result__isset __isset;

  bool operator == (const Spotify_getPlaylist_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Spotify_getPlaylist_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_getPlaylist_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_getPlaylist_presult__isset {
  _Spotify_getPlaylist_presult__isset() : success(false) {}
  bool success;
} _Spotify_getPlaylist_presult__isset;

class Spotify_getPlaylist_presult {
 public:


  virtual ~Spotify_getPlaylist_presult() throw() {}

  SpotifyPlaylist* success;

  _Spotify_getPlaylist_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Spotify_getPlaylistByName_args__isset {
  _Spotify_getPlaylistByName_args__isset() : cred(false), name(false) {}
  bool cred;
  bool name;
} _Spotify_getPlaylistByName_args__isset;

class Spotify_getPlaylistByName_args {
 public:

  Spotify_getPlaylistByName_args() : name("") {
  }

  virtual ~Spotify_getPlaylistByName_args() throw() {}

  SpotifyCredential cred;
  std::string name;

  _Spotify_getPlaylistByName_args__isset __isset;

  bool operator == (const Spotify_getPlaylistByName_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const Spotify_getPlaylistByName_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_getPlaylistByName_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_getPlaylistByName_pargs {
 public:


  virtual ~Spotify_getPlaylistByName_pargs() throw() {}

  const SpotifyCredential* cred;
  const std::string* name;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_getPlaylistByName_result__isset {
  _Spotify_getPlaylistByName_result__isset() : success(false) {}
  bool success;
} _Spotify_getPlaylistByName_result__isset;

class Spotify_getPlaylistByName_result {
 public:

  Spotify_getPlaylistByName_result() {
  }

  virtual ~Spotify_getPlaylistByName_result() throw() {}

  SpotifyPlaylist success;

  _Spotify_getPlaylistByName_result__isset __isset;

  bool operator == (const Spotify_getPlaylistByName_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Spotify_getPlaylistByName_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_getPlaylistByName_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_getPlaylistByName_presult__isset {
  _Spotify_getPlaylistByName_presult__isset() : success(false) {}
  bool success;
} _Spotify_getPlaylistByName_presult__isset;

class Spotify_getPlaylistByName_presult {
 public:


  virtual ~Spotify_getPlaylistByName_presult() throw() {}

  SpotifyPlaylist* success;

  _Spotify_getPlaylistByName_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Spotify_selectPlaylist_args__isset {
  _Spotify_selectPlaylist_args__isset() : cred(false), playlist(false) {}
  bool cred;
  bool playlist;
} _Spotify_selectPlaylist_args__isset;

class Spotify_selectPlaylist_args {
 public:

  Spotify_selectPlaylist_args() : playlist("") {
  }

  virtual ~Spotify_selectPlaylist_args() throw() {}

  SpotifyCredential cred;
  std::string playlist;

  _Spotify_selectPlaylist_args__isset __isset;

  bool operator == (const Spotify_selectPlaylist_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    if (!(playlist == rhs.playlist))
      return false;
    return true;
  }
  bool operator != (const Spotify_selectPlaylist_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_selectPlaylist_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_selectPlaylist_pargs {
 public:


  virtual ~Spotify_selectPlaylist_pargs() throw() {}

  const SpotifyCredential* cred;
  const std::string* playlist;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_merge2playlist_args__isset {
  _Spotify_merge2playlist_args__isset() : cred(false), pl(false), tracks(false) {}
  bool cred;
  bool pl;
  bool tracks;
} _Spotify_merge2playlist_args__isset;

class Spotify_merge2playlist_args {
 public:

  Spotify_merge2playlist_args() : pl("") {
  }

  virtual ~Spotify_merge2playlist_args() throw() {}

  SpotifyCredential cred;
  std::string pl;
  SpotifyPlaylist tracks;

  _Spotify_merge2playlist_args__isset __isset;

  bool operator == (const Spotify_merge2playlist_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    if (!(pl == rhs.pl))
      return false;
    if (!(tracks == rhs.tracks))
      return false;
    return true;
  }
  bool operator != (const Spotify_merge2playlist_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_merge2playlist_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_merge2playlist_pargs {
 public:


  virtual ~Spotify_merge2playlist_pargs() throw() {}

  const SpotifyCredential* cred;
  const std::string* pl;
  const SpotifyPlaylist* tracks;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_merge2playlist_result__isset {
  _Spotify_merge2playlist_result__isset() : success(false) {}
  bool success;
} _Spotify_merge2playlist_result__isset;

class Spotify_merge2playlist_result {
 public:

  Spotify_merge2playlist_result() : success(0) {
  }

  virtual ~Spotify_merge2playlist_result() throw() {}

  bool success;

  _Spotify_merge2playlist_result__isset __isset;

  bool operator == (const Spotify_merge2playlist_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Spotify_merge2playlist_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_merge2playlist_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_merge2playlist_presult__isset {
  _Spotify_merge2playlist_presult__isset() : success(false) {}
  bool success;
} _Spotify_merge2playlist_presult__isset;

class Spotify_merge2playlist_presult {
 public:


  virtual ~Spotify_merge2playlist_presult() throw() {}

  bool* success;

  _Spotify_merge2playlist_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Spotify_add2playlist_args__isset {
  _Spotify_add2playlist_args__isset() : cred(false), pl(false), track(false) {}
  bool cred;
  bool pl;
  bool track;
} _Spotify_add2playlist_args__isset;

class Spotify_add2playlist_args {
 public:

  Spotify_add2playlist_args() : pl("") {
  }

  virtual ~Spotify_add2playlist_args() throw() {}

  SpotifyCredential cred;
  std::string pl;
  SpotifyTrack track;

  _Spotify_add2playlist_args__isset __isset;

  bool operator == (const Spotify_add2playlist_args & rhs) const
  {
    if (!(cred == rhs.cred))
      return false;
    if (!(pl == rhs.pl))
      return false;
    if (!(track == rhs.track))
      return false;
    return true;
  }
  bool operator != (const Spotify_add2playlist_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_add2playlist_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_add2playlist_pargs {
 public:


  virtual ~Spotify_add2playlist_pargs() throw() {}

  const SpotifyCredential* cred;
  const std::string* pl;
  const SpotifyTrack* track;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_add2playlist_result__isset {
  _Spotify_add2playlist_result__isset() : success(false) {}
  bool success;
} _Spotify_add2playlist_result__isset;

class Spotify_add2playlist_result {
 public:

  Spotify_add2playlist_result() : success(0) {
  }

  virtual ~Spotify_add2playlist_result() throw() {}

  bool success;

  _Spotify_add2playlist_result__isset __isset;

  bool operator == (const Spotify_add2playlist_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Spotify_add2playlist_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_add2playlist_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_add2playlist_presult__isset {
  _Spotify_add2playlist_presult__isset() : success(false) {}
  bool success;
} _Spotify_add2playlist_presult__isset;

class Spotify_add2playlist_presult {
 public:


  virtual ~Spotify_add2playlist_presult() throw() {}

  bool* success;

  _Spotify_add2playlist_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Spotify_whats_playing_args {
 public:

  Spotify_whats_playing_args() {
  }

  virtual ~Spotify_whats_playing_args() throw() {}


  bool operator == (const Spotify_whats_playing_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Spotify_whats_playing_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_whats_playing_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Spotify_whats_playing_pargs {
 public:


  virtual ~Spotify_whats_playing_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_whats_playing_result__isset {
  _Spotify_whats_playing_result__isset() : success(false) {}
  bool success;
} _Spotify_whats_playing_result__isset;

class Spotify_whats_playing_result {
 public:

  Spotify_whats_playing_result() {
  }

  virtual ~Spotify_whats_playing_result() throw() {}

  SpotifyTrack success;

  _Spotify_whats_playing_result__isset __isset;

  bool operator == (const Spotify_whats_playing_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Spotify_whats_playing_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Spotify_whats_playing_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Spotify_whats_playing_presult__isset {
  _Spotify_whats_playing_presult__isset() : success(false) {}
  bool success;
} _Spotify_whats_playing_presult__isset;

class Spotify_whats_playing_presult {
 public:


  virtual ~Spotify_whats_playing_presult() throw() {}

  SpotifyTrack* success;

  _Spotify_whats_playing_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class SpotifyClient : virtual public SpotifyIf {
 public:
  SpotifyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  SpotifyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void initiateSession(SpotifyCredential& _return, const SpotifyCredential& cred);
  void send_initiateSession(const SpotifyCredential& cred);
  void recv_initiateSession(SpotifyCredential& _return);
  void logoutSession(const SpotifyCredential& cred);
  void send_logoutSession(const SpotifyCredential& cred);
  void sendCommand(const SpotifyCredential& cred, const SpotifyCmd::type cmd);
  void send_sendCommand(const SpotifyCredential& cred, const SpotifyCmd::type cmd);
  void search(SpotifyPlaylist& _return, const SpotifyCredential& cred, const SpotifySearch& criteria);
  void send_search(const SpotifyCredential& cred, const SpotifySearch& criteria);
  void recv_search(SpotifyPlaylist& _return);
  void getPlaylists(SpotifyPlaylistList& _return, const SpotifyCredential& cred);
  void send_getPlaylists(const SpotifyCredential& cred);
  void recv_getPlaylists(SpotifyPlaylistList& _return);
  void getPlaylist(SpotifyPlaylist& _return, const SpotifyCredential& cred, const int32_t plist_id);
  void send_getPlaylist(const SpotifyCredential& cred, const int32_t plist_id);
  void recv_getPlaylist(SpotifyPlaylist& _return);
  void getPlaylistByName(SpotifyPlaylist& _return, const SpotifyCredential& cred, const std::string& name);
  void send_getPlaylistByName(const SpotifyCredential& cred, const std::string& name);
  void recv_getPlaylistByName(SpotifyPlaylist& _return);
  void selectPlaylist(const SpotifyCredential& cred, const std::string& playlist);
  void send_selectPlaylist(const SpotifyCredential& cred, const std::string& playlist);
  bool merge2playlist(const SpotifyCredential& cred, const std::string& pl, const SpotifyPlaylist& tracks);
  void send_merge2playlist(const SpotifyCredential& cred, const std::string& pl, const SpotifyPlaylist& tracks);
  bool recv_merge2playlist();
  bool add2playlist(const SpotifyCredential& cred, const std::string& pl, const SpotifyTrack& track);
  void send_add2playlist(const SpotifyCredential& cred, const std::string& pl, const SpotifyTrack& track);
  bool recv_add2playlist();
  void whats_playing(SpotifyTrack& _return);
  void send_whats_playing();
  void recv_whats_playing(SpotifyTrack& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class SpotifyProcessor : virtual public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<SpotifyIf> iface_;
  virtual bool process_fn(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (SpotifyProcessor::*)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_initiateSession(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_logoutSession(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_sendCommand(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_search(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getPlaylists(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getPlaylist(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getPlaylistByName(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_selectPlaylist(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_merge2playlist(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_add2playlist(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_whats_playing(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  SpotifyProcessor(boost::shared_ptr<SpotifyIf> iface) :
    iface_(iface) {
    processMap_["initiateSession"] = &SpotifyProcessor::process_initiateSession;
    processMap_["logoutSession"] = &SpotifyProcessor::process_logoutSession;
    processMap_["sendCommand"] = &SpotifyProcessor::process_sendCommand;
    processMap_["search"] = &SpotifyProcessor::process_search;
    processMap_["getPlaylists"] = &SpotifyProcessor::process_getPlaylists;
    processMap_["getPlaylist"] = &SpotifyProcessor::process_getPlaylist;
    processMap_["getPlaylistByName"] = &SpotifyProcessor::process_getPlaylistByName;
    processMap_["selectPlaylist"] = &SpotifyProcessor::process_selectPlaylist;
    processMap_["merge2playlist"] = &SpotifyProcessor::process_merge2playlist;
    processMap_["add2playlist"] = &SpotifyProcessor::process_add2playlist;
    processMap_["whats_playing"] = &SpotifyProcessor::process_whats_playing;
  }

  virtual bool process(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~SpotifyProcessor() {}
};

class SpotifyMultiface : virtual public SpotifyIf {
 public:
  SpotifyMultiface(std::vector<boost::shared_ptr<SpotifyIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~SpotifyMultiface() {}
 protected:
  std::vector<boost::shared_ptr<SpotifyIf> > ifaces_;
  SpotifyMultiface() {}
  void add(boost::shared_ptr<SpotifyIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void initiateSession(SpotifyCredential& _return, const SpotifyCredential& cred) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->initiateSession(_return, cred);
        return;
      } else {
        ifaces_[i]->initiateSession(_return, cred);
      }
    }
  }

  void logoutSession(const SpotifyCredential& cred) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->logoutSession(cred);
    }
  }

  void sendCommand(const SpotifyCredential& cred, const SpotifyCmd::type cmd) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->sendCommand(cred, cmd);
    }
  }

  void search(SpotifyPlaylist& _return, const SpotifyCredential& cred, const SpotifySearch& criteria) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->search(_return, cred, criteria);
        return;
      } else {
        ifaces_[i]->search(_return, cred, criteria);
      }
    }
  }

  void getPlaylists(SpotifyPlaylistList& _return, const SpotifyCredential& cred) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getPlaylists(_return, cred);
        return;
      } else {
        ifaces_[i]->getPlaylists(_return, cred);
      }
    }
  }

  void getPlaylist(SpotifyPlaylist& _return, const SpotifyCredential& cred, const int32_t plist_id) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getPlaylist(_return, cred, plist_id);
        return;
      } else {
        ifaces_[i]->getPlaylist(_return, cred, plist_id);
      }
    }
  }

  void getPlaylistByName(SpotifyPlaylist& _return, const SpotifyCredential& cred, const std::string& name) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getPlaylistByName(_return, cred, name);
        return;
      } else {
        ifaces_[i]->getPlaylistByName(_return, cred, name);
      }
    }
  }

  void selectPlaylist(const SpotifyCredential& cred, const std::string& playlist) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->selectPlaylist(cred, playlist);
    }
  }

  bool merge2playlist(const SpotifyCredential& cred, const std::string& pl, const SpotifyPlaylist& tracks) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->merge2playlist(cred, pl, tracks);
      } else {
        ifaces_[i]->merge2playlist(cred, pl, tracks);
      }
    }
  }

  bool add2playlist(const SpotifyCredential& cred, const std::string& pl, const SpotifyTrack& track) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->add2playlist(cred, pl, track);
      } else {
        ifaces_[i]->add2playlist(cred, pl, track);
      }
    }
  }

  void whats_playing(SpotifyTrack& _return) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->whats_playing(_return);
        return;
      } else {
        ifaces_[i]->whats_playing(_return);
      }
    }
  }

};



#endif
