/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "spotify_constants.h"



const spotifyConstants g_spotify_constants;

spotifyConstants::spotifyConstants() {
}



